name: pipeline

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: test
        run: go test ./...

      - name: build
        run: go build -o app .
        env:
          GOOS: linux
          GOARCH: arm64

      - name: archive executable
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: .

      - run: chmod +x app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ulich/onedrive-cameraroll-renamer:latest,ulich/onedrive-cameraroll-renamer:${{ github.sha }}
          platforms: linux/arm64
